### ISSUE TITLE
output color issue

### ISSUE THREAD

**Issue by HuangShumin** [mengmo/QuickJS-Windows-Build#3] opened 2020-02-25 15:57 UTC
Hi, do you have any trick to fix the color display?
for example, when you input i=1 in qjs command line, it displays as below

[32;1mi[0m[J[D[32;1mi[0m[32;1m=[0m[J[2D[32;1mi[0m[32;1m=[0m[32m1[0m[J
[37;1m1

**Comment by mengmo** [comment] 2020-02-25 16:52
duplicate of https://github.com/mengmo/QuickJS-Windows-Build/issues/1

**Closed** 2020-02-28 17:15 UTC
Labels: duplicate
